services:
    db:
        image: postgres:17.2
        container_name: postgres
        restart: unless-stopped
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        networks:
            - my-network

networks:
    my-network:
        driver: bridge